events.listen('recipes', event => {

//Removed

event.remove({mod: 'exnihilosequentia'})
event.remove({mod: 'excompressum'})
event.remove({mod: 'exnihilothermal'})
event.remove({mod: 'exnihilomekanism'})
event.remove({mod: 'advancedrocketry'})
event.remove({id: 'cagedmobs:crafting/mobcage'})
event.remove({id: 'rftoolsbase:dimensionalshard'})
event.remove({id: 'advancedrocketry:liquidiocircuitboard'})
event.remove({id: 'minecraft:netherite_ingot'})
event.remove({id: 'minecraft:ender_eye'})
event.remove({id: 'industrialforegoing:iron_gear'})
event.remove({id: 'industrialforegoing:gold_gear'})
event.remove({id: 'industrialforegoing:diamond_gear'})
event.remove({id: 'waterstrainer:string_mesh'})
event.remove({id: 'minecraft:ens_ancient_debris'})
event.remove({id: 'tconstruct:smeltery/seared_block/seared_bricks'})
event.remove({id: 'tconstruct:smeltery/casting/metal/copper/ingot_sand_cast'})
event.remove({id: 'tconstruct:smeltery/casting/metal/copper/ingot_gold_cast'})
event.remove({id: 'tconstruct:smeltery/casting/metal/copper/nugget_gold_cast'})
event.remove({id: 'tconstruct:smeltery/casting/metal/copper/nugget_gold_cast'})
event.remove({id: 'tconstruct:smeltery/casting/metal/copper/block'})
event.remove({id: 'tconstruct:smeltery/casting/casts/blank'})
event.remove({id: 'waterstrainer:bait_pot'})
event.remove({id: 'minecraft:furnace'})
event.remove({id: 'ceramicbucket:unfired_clay_bucket'})
event.remove({id: 'ceramicshears:clay_shears_part'})
event.remove({id: 'industrialforegoing:block_breaker'})
event.remove({id: 'minecraft:glass'})
event.remove({id: 'mekanism:configurator'})
event.remove({id: 'mekanism:logistical_sorter'})
event.remove({id: 'mekanismgenerators:generator/gas_burning'})
event.remove({id: 'industrialforegoing:pitiful_generator'})
event.remove({id: 'minecraft:terracotta'})
event.remove({id: 'pipez:item_pipe'})
event.remove({id: 'pipez:fluid_pipe'})
event.remove({id: 'pipez:gas_pipe'})
event.remove({id: 'pipez:energy_pipe'})
event.remove({output: 'mekanism:scuba_tank'})
event.remove({output: 'thermal:rubber'})
event.remove({output: 'boss_tools:blast_furnace'})
event.remove({output: 'mysticalagriculture:master_infusion_crystal'})

event.remove({type: 'minecraft:smelting', input: '#forge:ores'})
event.remove({type: 'minecraft:blasting', input: '#forge:ores'})
event.remove({output: '#forge:gears', input: '#forge:nuggets'})
event.remove({output: '#forge:gears', input: '#forge:gems'})
event.remove({output: '#forge:gears', input: '#forge:plates'})
event.remove({output: '#forge:ingots', input: 'minecraft:fire_charge'})
event.remove({output: '#forge:dusts', input: 'thermal:earth_charge'})
event.remove({output: '#forge:gems', input: 'thermal:earth_charge'}) 

event.remove({type: 'botanypots:crop'})
event.remove({id: 'minecraft:compass'})
event.remove({id: 'morered:red_alloy_ingot_without_jumbo_furnace'})
event.remove({id: 'morered:stone_plate'})
event.remove({id: 'thermal:rf_coil'})
event.remove({id: 'thermal:redstone_servo'})
event.remove({id: 'morered:gatecrafting_plinth'})
event.remove({id: 'industrialforegoing:fluid_extractor'})
event.remove({id: 'thermal:devices/rock_gen/rock_gen_basalt'})
event.remove({id: 'mysticalagriculture:inferium_seeds'})
event.remove({id: 'matc:crystals/inferium'})
event.remove({id: 'matc:crystals/prudentium'})
event.remove({id: 'matc:crystals/tertium'})
event.remove({id: 'matc:crystals/imperium'})
event.remove({id: 'matc:crystals/supremium'})
event.remove({id: 'matc:crystals/master_infusion_crystal_superium'})
event.remove({id: 'refinedstorage:quartz_enriched_iron'})
event.remove({id: 'refinedstorage:silicon'})
event.remove({id: 'industrialforegoing:latex_processing_unit'})
event.remove({id: 'compactmachines:wall'})
event.remove({id: 'tconstruct:smeltery/alloys/molten_obsidian'})
event.remove({id: 'torchmaster:feral_flare_lantern'})
event.remove({id: 'factory:factory'})
event.remove({id: 'boss_tools:tinplaterezept'})
event.remove({id: 'boss_tools:iron_plate_rezept'})
event.remove({output: 'tconstruct:piggy_backpack'})
event.remove({output: 'industrialforegoing:dryrubber'})
event.remove({output: 'thermal:cured_rubber'})
event.remove({output: 'industrialforegoing:plastic'})
event.remove({output: 'libvulpes:blockcopper'})
event.remove({output: 'libvulpes:blocksteel'})
event.remove({output: 'libvulpes:blocktin'})

function peddusts(type){
event.remove({output: 'pedestals:dust' + type +''})
peddusts('gold')
peddusts('iron')
peddusts('gold')
peddusts('copper')
peddusts('tin')
peddusts('osmium')
peddusts('uranium')
peddusts('lead')
peddusts('silver')
peddusts('alumium')
peddusts('nickel')}

event.remove({id: 'pedestals:upgrades/itempedestalupgradedefault'})
event.remove({id: 'extendedcrafting:black_iron_ingot'})
event.remove({id: 'extendedcrafting:frame'})
event.remove({id: 'extendedcrafting:ultimate_singularity'})
event.remove({id: 'culinaryconstruct:culinary_station'})
event.remove({id: 'bhc:canister'})
event.remove({id: 'bhc:god_apple'})
event.remove({id: 'bhc:green_heart_canister'})
event.remove({id: 'bhc:yellow_heart_canister'})
event.remove({id: 'bhc:blue_heart_canister'})
event.remove({id: 'libvulpes:coalgenerator'})
event.remove({id: 'jaopca:thermal_expansion.material_to_gear.titanium'})

//event.remove({output: 'powah:dielectric_paste'})
//event.remove({id: 'angelring:itemring'})

})