#No comment
#Range: 0.0 ~ 10.0
breakSpeedAquaAffinity = 0.25
#No comment
breakSpeedChanges = false
#No comment
movementChanges = false
#No comment
oxygenChanges = false
#modid:entity, oxygenCapacity
oxygenProviderEntities = []
#modid:item, maxDivingDepth
divingMaskProviderItems = ["better_diving:diving_mask, 40", "better_diving:rebreather, 60", "better_diving:reinforced_diving_mask, 40"]
#modid:item, mainhand, offhand, feet, legs, chest, head, oxygenCapacity, needsDivingMask
oxygenProviderItems = ["better_diving:standard_o2_tank, false, false, false, false, true, false, 600, true", "better_diving:high_capacity_o2_tank, false, false, false, false, true, false, 1800, true", "better_diving:reinforced_o2_tank, false, false, false, false, true, false, 600, true"]
#modid:item, mainhand, offhand, feet, legs, chest, head, miningspeedBonus
miningspeedProviderItems = ["better_diving:wetsuit_leggings, false, false, false, true, false, false, 0.15", "better_diving:improved_wetsuit_leggings, false, false, false, true, false, false, 0.3", "better_diving:reinforced_wetsuit_leggings, false, false, false, true, false, false, 0.15"]
#modid:item, mainhand, offhand, feet, legs, chest, head, swimspeedBonus
swimspeedProviderItems = ["better_diving:fins, false, false, true, false, false, false, 0.1667", "better_diving:ultra_glide_fins, false, false, true, false, false, false, 0.3333", "better_diving:reinforced_fins, false, false, true, false, false, false, 0.1667"]

[powerCell]
	#No comment
	#Range: > 0
	maxReceive = 5000
	#No comment
	#Range: > 0
	maxExtract = 500
	#No comment
	#Range: > 0
	capacity = 2000000
	#No comment
	#Range: > 0
	energy = 2000000

[divingGear]
	#No comment
	#Range: 0 ~ 1000000
	durability = 60
	#No comment
	protection = [1, 3, 5, 1]
	#No comment
	#Range: 0.0 ~ 1000.0
	toughness = 0.0
	#No comment
	#Range: 0 ~ 1000
	enchantability = 10
	#No comment
	#Range: -1.0 ~ 1.0
	knockbackResistance = 0.0

[improvedDivingGear]
	#No comment
	#Range: 0 ~ 1000000
	durability = 60
	#No comment
	protection = [1, 3, 5, 1]
	#No comment
	#Range: 0.0 ~ 1000.0
	toughness = 0.0
	#No comment
	#Range: 0 ~ 1000
	enchantability = 10
	#No comment
	#Range: -1.0 ~ 1.0
	knockbackResistance = 0.0

[reinforcedDivingGear]
	#No comment
	#Range: 0 ~ 1000000
	durability = 80
	#No comment
	protection = [2, 5, 7, 2]
	#No comment
	#Range: 0.0 ~ 1000.0
	toughness = 0.5
	#No comment
	#Range: 0 ~ 1000
	enchantability = 10
	#No comment
	#Range: -1.0 ~ 1.0
	knockbackResistance = 0.0

[movement]
	#No comment
	#Range: 0 ~ 2
	depthStriderOperation = 1
	#No comment
	offhandModifier = true
	#No comment
	#Range: -1.0 ~ 1.0
	mainhandAmount = -0.05
	#No comment
	#Range: -1.0 ~ 1.0
	dolphinsGraceAmount = 1.0
	#No comment
	#Range: 0 ~ 2
	overwaterOperation = 1
	#No comment
	#Range: -1.0 ~ 1.0
	depthStriderAmount = 0.1
	#No comment
	#Range: -1.0 ~ 1.0
	hungerAmount = -0.5
	#No comment
	#Range: 0 ~ 2
	mainhandOperation = 2
	#No comment
	#Range: 0.0 ~ 1.0
	baseSwimSpeed = 0.04
	#No comment
	#Range: 0.0 ~ 1.0
	hungerThreshold = 0.2
	#No comment
	overwaterModifier = true
	#No comment
	#Range: 0 ~ 2
	dolphinsGraceOperation = 1
	#No comment
	mainhandModifier = true
	#No comment
	#Range: -1.0 ~ 1.0
	divingAmount = 0.2
	#No comment
	#Range: 0 ~ 2
	hungerOperation = 2
	#No comment
	#Range: -1.0 ~ 1.0
	overwaterAmount = 0.2
	#No comment
	hungerModifier = true
	#No comment
	#Range: 0 ~ 2
	divingOperation = 1
	#No comment
	#Range: -1.0 ~ 1.0
	offhandAmount = -0.05
	#No comment
	#Range: 0 ~ 2
	offhandOperation = 2

[oxygen]
	#No comment
	oxygenEfficiency = true
	#No comment
	#Range: 0 ~ 1000000
	oxygenCapacityRespiration = 300
	#No comment
	#Range: 0 ~ 1024
	oxygenBaseDivingDepth = 20
	#No comment
	#Range: 0 ~ 1000000
	oxygenCapacity = 900
	#No comment
	#Range: 1 ~ 1024
	oxygenEfficiencyRate = 4

[seamoth]
	#No comment
	#Range: 0.0 ~ 1.0
	seamothSpeed = 0.0275
	#No comment
	#Range: 0 ~ 1000000
	seamothEnergyUsage = 100

